name: Terraform provider lint
on:
  push:
    paths:
      - '**.go'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
jobs:
  tfproviderlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
    - uses: bflad/tfproviderlint-github-action@master # TSCCR: no entry for action: "bflad/tfproviderlint-github-action"
      with:
        args: ./...
